version: "3.7"
 
services:
  app:
    image: "karshak06/devops-for-programmers-project-74"
    build:
      context: .
      dockerfile: Dockerfile.production
    volumes:
      - "./app:/app"
    command: bash -c "npm ci"
