version: "3.7"
 
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - "./app:/app"
    command:  bash -c "npm run dev"
    
  caddy:
    image: caddy/caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./app/:/srv
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile